# Generated by Django 6.0.4 on 2026-05-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(default='Your Name', max_length=100)),
                ('tagline', models.CharField(default='researcher · builder · occasional overthinker', max_length=200)),
                ('about', models.TextField(default='I work at the intersection of things I find interesting. This is where I put them into words.')),
                ('avatar_emoji', models.CharField(default='🌿', max_length=10)),
                ('socials_json', models.TextField(default='[]')),
            ],
            options={
                'verbose_name': 'Site Config',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(max_length=300),
        ),
    ]
