# Generated by Django 6.0.4 on 2026-05-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_siteconfig_alter_post_content_alter_post_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
